" ###########################################################
" ##########               VIMRC file by smy               ##
" ###########################################################
"----------Configuration-----------------------------{{{

" Bail out if something that ran earlier, e.g. a system wide vimrc, does not
" want Vim to use these default values.
if exists('skip_defaults_vim')
  finish
endif

"filetype plugin indent on  " enable filetype recognitions and indent base on it

set nocompatible               " Use Vim settings, rather than Vi settings (much better!).
set viminfo=<1000,'1000,/50,:100,h,f1

set backspace=indent,eol,start  " Allow backspacing over everything in insert mode.
if has('unnamedplus')           " use the system register for everything
   set clipboard=unnamed,unnamedplus
endif
set display=truncate            " Show @@@ in the last line if it is truncated.
set encoding=utf-8              " Unicode encoding support
set foldcolumn=2                " width of fold column
set foldmethod=marker           " set folding mode
"use rg instead of grep
" set grepprg=rg\ --vimgrep\ --smart-case\ --follow
set hidden                      " Allow hidden buffers, don't limit to 1 file per window/split
set history=200		            " keep 200 lines of command line history
set hlsearch                    " Switch on highlighting the last used search pattern.
set ignorecase                  " set ignore small/capital for search
set incsearch                   " Display the match for a search pattern when halfway typing it
set laststatus=2                " show statusline always
set mouse=a                     " use mouse everywhere
set nrformats-=octal            " do not recognize octal numbers for ctrl-a and ctrl-x
set number relativenumber       " Show line numbers & relativenumber
"" set ruler		                 " show the cursor position all the time
set scrolloff=5                 " Show a few lines of context around the cursor.
set sidescrolloff=5	        	" Vertical
set showcmd		               " display incomplete commands
set showmatch                 " When selecting a parenthesis it will highlight the one matching
set smartcase                   " set smartcase for search
" set splitbelow splitright
" set spell                     " set spellchecking
set spelllang=en_us,ru_ru
" set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P
" set statusline=%f%m%r%h%w\ [%Y]\ [0x%02.2B]%<\ %F%=%4v,%4l\ of\ %L\ %3p%%
set ttimeout		            " time out for key codes
set ttimeoutlen=500	            " wait up to 500ms after Esc for special key
set vb "disable beep sound
set wildmenu		            " display completion matches in a status line
set wildmode=longest,list,full  " wildmode insertions
set updatetime=250				" for vimgutter
syntax enable                   " Switch syntax highlighting on
filetype on

"Autosave & swap
set autowriteall		" This will save the file when you switch buffers, make it etc.
"						"autosave everything with ignoring warnings from untitled buffers,
"						"and read-only files, etc
autocmd FocusLost * silent! wa
" save everytime text changed in normal mode, THIS BREAK quickfix-reflector!!!
autocmd TextChanged * silent! write
set nobackup
set noswapfile
set undofile " Maintain undo history
set undodir=~/.vim/undodir
set undolevels=10000     " Maximum number of changes that can be undone
set undoreload=10000
" set vimwiki tags
set tags+=$HOME/Vimwiki/tags.wiki
"Langmap for Russian layout
"no <">, <?>, <;>, </> - try to find way to write in codes
" set langmap=!№%*ёйцукенгшщзхъфывапролджэячсмитьбюЁЙЦУКЕHГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ;!#%*`qwertyuiop[]asdfghjkl\\;'zxcvbnm\\,.~QWERTYUIOP{}ASDFGHJKL:\\"ZXCVBNM<>
" set nolangremap
set keymap=russian-jcukenwin
set iminsert=0 " Чтобы при старте ввод был на английском, а не русском (start > i)
set imsearch=0 " Чтобы при старте поиск был на английском, а не русском (start > /)
"switch C-^

"Tabs and Indent
set autoindent         "when creating a new line, copy the indentation from the line above
set copyindent         "copy the previous indentation on autoindenting
set smartindent      "Do smart autoindenting when starting a new line.
" set expandtab        " [I] < > instead Tab. Real tab -> CTRL-V<Tab>.
set noexpandtab        "don't expand tabs to spaces by default
set smarttab           "when deleting whitespace at the beginning of a line, delete 1 tab worth of spaces
set shiftwidth=4       "Number of spaces to use for each step of (auto)indent
set shiftround         "Use multiple of shiftwidth when indenting with '<' and '>'
set softtabstop=4      "Number of spaces that a <Tab> counts for while performing editing operations
set tabstop=4          "Number of spaces that a <Tab> in the file counts for.
set wrap               "Wrap lines
set linebreak

set nolist
set listchars=tab:»-,space:·,nbsp:~,trail:-,eol:$
" highlight SpecialKey ctermfg=8 guifg=DimGrey
" highlight SpecialKey ctermfg=14 guifg=Yellow

" white space characters
" set nolist
" compatible space chars
" set listchars=eol:$,tab:.\ ,trail:.,extends:>,precedes:<,nbsp:_
" incompatible with debian stretch
" set listchars=eol:↓,tab:\ \ ┊,trail:●,extends:…,precedes:…,space:·
" highlight SpecialKey term=standout ctermfg=darkgray guifg=darkgray

" Ignoring file types from autocomplition:
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png

"Cursor Cross
"must add right color scheme OR experement with set guicolor
set cursorline
set cursorcolumn
highlight CursorLine ctermbg=Yellow cterm=bold guibg=#f9ed07
" highlight CursorColumn ctermbg=Yellow cterm=bold guibg=#000000
" colorsheme XXXXXXXXXXXXXXXx

"Remove pipes | that act as separators on slits
set fillchars+=vert:\

" MArkdown
let g:markdown_folding = 1
"}}}
"----------Autocmd------------{{{

" textwidth = 78
augroup vimrcEx
  au!
  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

"cursor position
augroup vimStartup
  au!

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid, when inside an event handler
  " (happens when dropping a file on gvim) and for a commit message (it's
  " likely a different one than last time).
  autocmd BufReadPost *
    \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
    \ |   exe "normal! g`\""
    \ | endif
augroup END
" Put these in an autocmd group, so that you can revert them with:
" ":augroup vimStartup | au! | augroup END"

" Make views automatic !!!!!!!!!!!!!
autocmd BufWinLeave *.* mkview!
autocmd BufWinEnter *.* silent loadview
" autocmd BufWinLeave * if expand("%") != "" | mkview | endif
" autocmd BufWinEnter * if expand("%") != "" | loadview | endif
" autocmd BufWinLeave ?* mkview!
" autocmd BufWinEnter ?* silent loadview

" Highlight cursorline ONLY in the active window:
au WinEnter * setlocal cursorline
au WinLeave * setlocal nocursorline

" remove whitespaces on save
" autocmd BufWritePre * :%s/\s\+$//e

" Filetype autocmd
" autocmd BufReadPost,BufNewFile,BufRead  *.txt  set filetype=txt
" autocmd BufEnter diary.wiki :VimwikiDiaryGenerateLinks

" In the quickfix window, <CR> is used to jump to the error under the
" cursor, so undefine the mapping there.
autocmd BufReadPost quickfix nnoremap <buffer> <CR> <CR>

" Working projects
" ansible inventory yaml
autocmd BufRead,BufNewFile ~/Git_work/*/inventory/*/* set filetype=yaml
autocmd BufRead,BufNewFile ~/Git_work/*/*/group_vars/* set filetype=yaml
autocmd BufRead,BufNewFile ~/Share/Git_work/*/inventory/*/* set filetype=yaml
autocmd BufRead,BufNewFile ~/Share/Git_work/*/*/group_vars/* set filetype=yaml
autocmd BufRead,BufNewFile ~/.ansible/*/inventory/* set filetype=yaml
autocmd BufRead,BufNewFile ~/.ansible/*/group_vars/* set filetype=yaml
autocmd BufRead,BufNewFile ~/.ansible/*/*.yml set filetype=yaml


" }}}
"--------- PLUGINS & FILES {{{
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif

" VIM-PLUG
" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')
" Declare the list of plugins.
" For problems with git promtp - use full url
Plug 'airblade/vim-gitgutter'
Plug 'brianrodri/vim-sort-folds'
Plug 'chrisbra/unicode.vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'dpelle/vim-LanguageTool'
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'lambdalisue/fern-git-status.vim'
Plug 'lambdalisue/fern-hijack.vim'
Plug 'lambdalisue/fern-mapping-git.vim'
Plug 'lambdalisue/fern-mapping-project-top.vim'
Plug 'lambdalisue/fern-renderer-nerdfont.vim'
Plug 'lambdalisue/fern-ssh'
Plug 'lambdalisue/fern.vim'
Plug 'lambdalisue/nerdfont.vim'
Plug 'liuchengxu/vim-which-key'
Plug 'mattn/calendar-vim'
Plug 'romainl/vim-qf'
Plug 'stefandtw/quickfix-reflector.vim'
Plug 'madox2/vim-ai'
Plug 'stsewd/fzf-checkout.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-rsi'
Plug 'tpope/vim-speeddating' 
Plug 'tpope/vim-unimpaired'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vimwiki/vimwiki'
" List ends here. Plugins become visible to Vim after this call.
call plug#end()
"____________ Vimwiki_____________________________
let g:vimwiki_folding='syntax'
let g:vimwiki_global_ext = 0
let g:vimwiki_hl_headers = 1
let g:vimwiki_conceal_pre = 1
let g:vimwiki_url_maxsave = 0
let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
let g:vimwiki_nested_syntaxes = {'python': 'python', 'bash':'bash', 'sql':'sql', 'msql':'msql', 'git':'git',
            \'gitcommit':'gitcommint', 'vim':'vim', 'viminfo':'viminfo', 'c':'c', 'c++': 'cpp', 'conf':'conf',
            \'config':'config', 'cfg':'cfg', 'cmake':'cmake', 'diff':'diff', 'zsh':'zsh',
            \'xdefaults':'xdefaults'}
" Final exp
let g:vimwiki_root = '~/Dropbox/Vimwiki'
let g:vimwiki_list = [
            \{'path': '~/Dropbox/Vimwiki/linux2', 'syntax': 'markdown', 'ext':'.md', 'auto_toc': 1},
            \{'path': '~/Dropbox/Vimwiki/work', 'syntax': 'markdown', 'ext':'.md', 'auto_toc': 1},
            \{'path': '~/Dropbox/Vimwiki', 'syntax': 'markdown', 'ext': '.md', 'auto_toc': 1},
            \{'path': '~/Dropbox/Vimwiki/notes', 'syntax': 'markdown', 'ext':'.md', 'auto_toc': 1},
            \{'path': '~/Dropbox/Vimwiki/lists', 'syntax': 'markdown', 'ext':'.md', 'auto_toc': 1},
            \{'path': '~/Dropbox/Vimwiki/links', 'syntax': 'markdown', 'ext':'.md', 'auto_toc': 1},
            \{'path': '~/Dropbox/Vimwiki/soft', 'syntax': 'markdown', 'ext':'.md', 'auto_toc': 1},
            \{'path': '~/Dropbox/Vimwiki/hardware', 'syntax': 'markdown', 'ext':'.md', 'auto_toc': 1},
            \{'path': '~/Dropbox/Vimwiki/selfimprove', 'syntax': 'markdown', 'ext':'.md', 'auto_toc': 1},
            \{'path': '~/Dropbox/Vimwiki/life', 'syntax': 'markdown', 'ext':'.md', 'auto_toc': 1}]

" let g:vimwiki_map_prefix = '<Plug>'
" let g:vimwiki_no_default_links = 1

" command! Diary exe 'VimwikiDiaryIndex' | exe 'norm ggdGo' | exe 'VimwikiDiaryGenerateLinks' | exe 'norm zR'
" return to wiki diary and generate links
command! Diary exe 'VimwikiDiaryIndex' | exe 'VimwikiDiaryGenerateLinks'

function! VimwikiFindIncompleteTasks()
  lvimgrep /- \[ \]/ %:p
  lopen
endfunction

function! VimwikiFindAllIncompleteTasks()
  VimwikiSearch /- \[ \]/
  lopen
endfunction
"-----------------------------

" FERN
let g:fern#disable_default_mappings   = 1
let g:fern#disable_drawer_auto_quit   = 1
let g:fern#disable_viewer_hide_cursor = 1
let g:fern#renderer = "nerdfont"

function! FernInit() abort
  nmap <buffer><expr>
        \ <Plug>(fern-my-open-expand-collapse)
        \ fern#smart#leaf(
        \   "\<Plug>(fern-action-open:select)",
        \   "\<Plug>(fern-action-expand)",
        \   "\<Plug>(fern-action-collapse)",
        \ )
  nmap <buffer> <CR> <Plug>(fern-my-open-expand-collapse)
  nmap <buffer> <2-LeftMouse> <Plug>(fern-my-open-expand-collapse)
  nmap <buffer> z <Plug>(fern-action-hidden)
  nmap <buffer> C <Plug>(fern-action-clipboard-copy)
  nmap <buffer> D <Plug>(fern-action-remove)
  nmap <buffer> K <Plug>(fern-action-mark:clear)
  nmap <buffer> M <Plug>(fern-action-clipboard-move)
  nmap <buffer> N <Plug>(fern-action-new-path)
  nmap <buffer> P <Plug>(fern-action-clipboard-paste)
  nmap <buffer> R <Plug>(fern-action-rename)
  nmap <buffer> S <Plug>(fern-action-open:split)
  nmap <buffer> c <Plug>(fern-action-copy)
  nmap <buffer> f <Plug>(fern-action-include)
  nmap <buffer> h <Plug>(fern-action-collapse)
  nmap <buffer> gs <Plug>(fern-action-git-stage)
  nmap <buffer> gu <Plug>(fern-action-git-unstage)
  nmap <buffer> l <Plug>(fern-action-open-or-expand)
  nmap <buffer> m <Plug>(fern-action-mark:toggle)j
  nmap <buffer> r <Plug>(fern-action-reload)
  nmap <buffer> s <Plug>(fern-action-open:select)
  nmap <buffer> v <Plug>(fern-action-open:vsplit)
  nmap <buffer> y <Plug>(fern-action-yank)
  nmap <buffer> <nowait> < <Plug>(fern-action-leave)
  nmap <buffer> <nowait> > <Plug>(fern-action-enter)
endfunction

"  automatically update the current tree upon entering the fern window
augroup FernTypeGroup
    autocmd! * <buffer>
    autocmd BufEnter <buffer> silent execute "normal \<Plug>(fern-action-reload)"
augroup END

augroup FernEvents
  autocmd!
  autocmd FileType fern call FernInit()
augroup END

" fern-git-status
let g:fern_git_status#disable_ignored    = 1
" let g:fern_git_status#disable_untracked  = 1
let g:fern_git_status#disable_submodules = 1


"---------------
" Airline
"To allow powerline symbols to be seen
let g:airline_powerline_fonts=1
" let g:airline_symbols_ascii = 1

" Enable the list of buffers
" let g:airline#extensions#tabline#enabled = 1
" ~/full/path-to/file-name.js
" let g:airline#extensions#tabline#formatter = 'default'  " f/p/file-name.js
" let g:airline#extensions#tabline#formatter = 'jsformatter' " path-to/f
" let g:airline#extensions#tabline#formatter = 'unique_tail' " file-name.js
" let g:airline#extensions#tabline#formatter = 'unique_tail_improved' " f/p/file-name.js

" enable fugitive statusline - work without it
" let g:airline#extensions#branch#enabled = 1
" let g:airline_section_b = "%3p"
let g:airline#extensions#whitespace#enabled = 0 
let g:airline_theme='solarized'
"Reduces the space occupied by section z
" let g:airline_section_z = "%3p%% %l:%c"
"To allow colors in the status line
" set t_Co=256

" Note: You must define the dictionary first before setting values.
" Also, it's a good idea to check whether it exists as to avoid
" accidentally overwriting its contents.
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
" powerline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = '☰'
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.dirty='⚡'
let g:airline_symbols.whitespace = 'Ξ'
" If you only see boxes here it may be because your system doesn't have
" the correct fonts. Try it in vim first and if that fails see the help
" pages for vim-airline :help airline-troubleshooting

" FURGITIVE

"Vimgutter
let g:gitgutter_map_keys = 0

" Languagetool
" not work with modern version of Languagetool
" https://github.com/dpelle/vim-LanguageTool/issues/33
" now must use unzip version 5.9
let g:languagetool_jar='/home/freeman/Soft/LanguageTool-5.9/languagetool-commandline.jar'
" for archlinux
" let g:languagetool_cmd='/sbin/languagetool'
" let g:languagetool_cmd='java -jar /usr/share/java/languagetool/languagetool-commandline.jar'

"MarkdownPreview Config



"}}}
"----------Commands-------------------------{{{
" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
" Revert with: ":delcommand DiffOrig".
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif
" }}}
" ----------Funtions----------{{{
" Creating tags
function! AddTag(tagname)
    let tagname = input('Tag name: ', a:tagname, 'tag')
    let tagfile = expand('%:p')
    let tagaddress = input('Address: ', '/\<' . a:tagname . '\>/')
    if (tagname == ''  || tagaddress == '')
        return
    endif
    let cmd = '!echo -e "' . tagname . '\t' . tagfile .
        '\t' . tagaddress . '" >> ' . $HOME . '/tags.global'
    execute cmd
endfunction

" Wrap mode, move cursor by display lines when wrappong
function ToggleWrap()
  if &wrap
    echo "Wrap OFF"
    setlocal nowrap
    " set virtualedit=all
    silent! nunmap <buffer> k
    silent! nunmap <buffer> j
    silent! vunmap <buffer> k
    silent! vunmap <buffer> j
    silent! nunmap <buffer> 0
    silent! nunmap <buffer> $
    silent! nunmap <buffer> <Home>
    silent! nunmap <buffer> <End>
  else
    echo "Wrap ON"
    setlocal wrap linebreak
    " set virtualedit=
    " setlocal display+=lastline
    noremap <buffer> <silent> k gk
    noremap <buffer> <silent> j gj
    noremap <buffer> <silent> 0 g0
    noremap <buffer> <silent> $ g$
    vnoremap <buffer> <silent> j gj
    vnoremap <buffer> <silent> k gk
    noremap <buffer> <silent> <Home> g<Home>
    noremap <buffer> <silent> <End>  g<End>
  endif
endfunction

"for quickfix list
function! QuickfixMapping()
  " Go to the previous location and stay in the quickfix window
  nmap <buffer> K <Plug>(qf_qf_previous)zz<C-w>w

  " Go to the next location and stay in the quickfix window
  nmap <buffer> J <Plug>(qf_qf_next)zz<C-w>w
endfunction

augroup quickfix_group
    autocmd!
    autocmd filetype qf call QuickfixMapping()
augroup END
" autocmd TextChanged * silent! write

" Wrap visual selection in an JIRA {noformat} tag.
vmap <Leader>w <Esc>:call VisualHTMLTagWrap()<CR>
function! VisualHTMLTagWrap()
  " let tag = input("Tag to wrap block: ")
  let tag = 1
  if len(tag) > 0
    normal `>
    if &selection == 'exclusive'
      exe "normal o"
      exe "normal o{noformat}"
    else
      exe "normal o"
      " exe "normal o</".tag.">"
      exe "normal o{noformat}"
    endif
    normal `<
    exe "normal O{noformat}"
    " exe "normal O<".tag.">"
    normal `<
  endif
endfunction

" vmap <Leader>w <Esc>:call VisualHTMLTagWrap()<CR>
" function! VisualHTMLTagWrap()
"   " let tag = input("Tag to wrap block: ")
"   let tag = 1
"   if len(tag) > 0
"     normal `>
"     if &selection == 'exclusive'
"       exe "normal o```"
"     else
"       " exe "normal o</".tag.">"
"       exe "normal o```"
"     endif
"     normal `<
"     exe "normal O```bash"
"     " exe "normal O<".tag.">"
"     normal `<
"   endif
" endfunction



" }}}
"----------THEMES & COLORS----------------{{{
" set termguicolors "use true color

" fold color
" hi Folded cterm=bold ctermfg=DarkBlue ctermbg=none
" hi FoldColumn cterm=bold ctermfg=DarkBlue ctermbg=none

" search color
highlight Search ctermbg=3 ctermfg=0 cterm=none

"set cursorline
set cursorline
highlight CursorLine ctermbg=7 cterm=none

"---Solarized----
" set background=light
" let g:solarized_termcolors=256
" let g:solarized_contrast="high"
" colorscheme solarized

"}}}
"----------KEYMAPPINGS-------------------------{{{
"^^^^^^^^main^^^^^^^^^^^^^^^
" Don't use Ex mode, use Q for formatting.
" Revert with ":unmap Q".
map Q gq
nnoremap Y y$

"^^^^^Leader mapping & WhichKey^^^^
let g:mapleader = "\<Space>"
let g:maplocalleader = ','
nnoremap <silent> <leader>      :<C-u>WhichKey '<Space>'<CR>
nnoremap <silent> <localleader> :<C-u>WhichKey  ','<CR>
vnoremap <silent> <leader> :<C-u>WhichKeyVisual '<Space>'<CR>
call which_key#register('<Space>', "g:which_key_map", 'n')
call which_key#register('<Space>', "g:which_key_map_visual", 'v')
let g:which_key_map =  {}
let g:which_key_map['e'] = {
        \ 'name' : 'rename files' ,
		\ '1' : [':% norm /\(19\|20\)\d\{2}/yw0Pa - ', 'move movies date to begining'],
		\ '2' : [':% norm 0df]$hhhP0x', 'move anime group to end'],
		\ '3' : [':%s/.zip/.cbz/g', 'rename zip to cbz'],
		\ '4' : [':%s/.rar/.cbr/g', 'rename rar to cbr'],
		\ }
let g:which_key_map['d'] = {
        \ 'name' : 'Fern' ,
		\ 'd' : [':Fern . -drawer -width=35 -toggle', 'toggles a left-hand side project drawer on a current working directory'],
		\ 'f' : [':Fern . -drawer -reveal=% -width=35', 'opens fern and reveals the current buffer in the project tree'],
		\ 'c' : [':Fern %:h -drawer -width=35', 'opens just the directory of sibling files of the current buffer'],
		\ }
nnoremap <leader>cc @='i```<C-V><Enter><C-V><Enter><C-V><Enter><C-V><Enter>```<C-V><Esc>'<CR>
nnoremap <leader>cb @='i```bash<C-V><Enter><C-V><Enter><C-V><Enter><C-V><Enter>```<C-V><Esc>'<CR>
nnoremap <leader>cp @='i```python<C-V><Enter><C-V><Enter><C-V><Enter><C-V><Enter>```<C-V><Esc>'<CR>
nnoremap <leader>cs @='i```sql<C-V><Enter><C-V><Enter><C-V><Enter><C-V><Enter>```<C-V><Esc>'<CR>
nnoremap <leader>cg @='i```git<C-V><Enter><C-V><Enter><C-V><Enter><C-V><Enter>```<C-V><Esc>'<CR>
nnoremap <leader>cv @='i```vim<C-V><Enter><C-V><Enter><C-V><Enter><C-V><Enter>```<C-V><Esc>'<CR>
nnoremap <leader>ct :VimwikiTOC<CR>
let g:which_key_map['c'] = {
        \ 'name' : 'code block' ,
		\ 'c' : 'quotes blank',
		\ 'b' : 'bash',
		\ 'p' : 'python',
		\ 's' : 'sql',
		\ 'g' : 'git',
		\ 'v' : 'vim',
		\ 't' : 'VimwikiTOC',
		\ }
nnoremap <Leader>ft @='ciW**<C-V><C-R>"**<C-V><Esc>w'<CR>
nnoremap <Leader>fb :exe "norm I**" <bar> exe "norm A**"<CR>
nnoremap <Leader>fi @='ciW_<C-V><C-R>"_<C-V><Esc>w'<CR>
nnoremap <Leader>fI :exe "norm I_" <bar> exe "norm A_"<CR>
nnoremap <Leader>fc @='ciW`<C-V><C-R>"`<C-V><Esc>w'<CR>
nnoremap <Leader>fC :exe "norm I`" <bar> exe "norm A`"<CR>
nnoremap <Leader>fe @='ciW[[#<C-V><C-R>"]]<C-V><Esc>w'<CR>
" nnoremap <leader>fp :let a = ['</pre>', '<pre>'] <bar> %s/{noformat}/\=reverse(a)[0]/g<CR>
nnoremap <leader>fp :let a = ['```', '```bash'] <bar> %s/{noformat}/\=reverse(a)[0]/g<CR>
let g:which_key_map['f'] = {
        \ 'name' : 'text format' ,
		\ 't' : 'world in bold',
		\ 'b' : 'line in bold',
		\ 'i' : 'world in cursive',
		\ 'I' : 'line in cursive',
		\ 'c' : 'world in quotes',
		\ 'C' : 'line in quotes',
		\ 'e' : '[[#]]',
		\ 'p' : 'noformat to pre',
		\ }

"quickly fix spelling mistakes [gets rid of spellchecking]
nnoremap <Leader>fs 1z=
"shell check
" using https://www.shellcheck.net/ - install first
nnoremap <leader>a :silent !xdg-open <C-R>=escape("<C-R><C-F>", "#?&;\|%")<CR><CR> :redraw!<CR>
nnoremap <leader>b <Plug>VimwikiGoBackLink
nnoremap <leader>ds1 "=strftime("%Y-%m-%d %H:%M:%S")<CR>P
nnoremap <leader>ds2 "=strftime("%Y-%m-%d")<CR>P
nnoremap <leader>gb :Git blame<CR>
nnoremap <leader>gc :Git commit<CR>
nnoremap <leader>gdf :Gdiff<CR>
nnoremap <leader>gdh :Ghdiffsplit<CR>
" fetches the hunk from the merge parent (on the right)
nnoremap <leader>gdj :diffget //3<CR>
" fetches the hunk from the target parent (on the left)
" CHECK if need to add :diffupdate
nnoremap <leader>gdf :diffget //2<CR>
nnoremap <leader>gdv :Gvdiffsplit<CR>
nnoremap <leader>gg :GBrowse<CR>
nnoremap <leader>ghl :GitGutterLineHighlightsToggle<CR>
nnoremap <leader>ghp <Plug>(GitGutterPreviewHunk)
nnoremap <leader>ghs <Plug>(GitGutterStageHunk)
nnoremap <leader>ghu <Plug>(GitGutterUndoHunk)
nnoremap <leader>gl :Gclog<CR>
nnoremap <leader>grr :Gread<CR>
nnoremap <leader>gs :Git<CR>
nnoremap <leader>gw :Gwrite<CR>
nnoremap <leader>h :split<CR>
nnoremap <leader>j J
nnoremap <leader>l :ls<CR>:b<space>
nnoremap <leader>ma :vim /$alt+\\|<A-\\|Altmap\\|M-/ ~/.config/i3/config ~/.config/vifm/vifmrc ~/.config/tmux/tmux.conf ~/.vim/vimrc<CR>
nnoremap <leader>mc :vim /<C-/ ~/.config/i3/config ~/.config/vifm/vifmrc ~/.config/tmux/tmux.conf ~/.vim/vimrc<CR>
nnoremap <leader>ms :vim /<S-\\|S-/ ~/.config/i3/config ~/.config/vifm/vifmrc ~/.config/tmux/tmux.conf ~/.vim/vimrc<CR>
nnoremap <leader>m1 :autocmd! TextChanged *<CR>
nnoremap <leader>m2 :autocmd TextChanged * silent! write<CR>
nnoremap <leader>m8 :LanguageToolCheck<CR>
nnoremap <leader>m9 :LanguageToolClear<CR>
nnoremap <leader>o :only<CR>
nnoremap <leader>p :b#<CR>
nnoremap <leader>q <Plug>(qf_qf_toggle)
nnoremap <leader>rc :e $MYVIMRC<CR>
nnoremap <leader>rr :source ~/.vim/vimrc<CR>
nnoremap <leader>S :!clear && shellcheck %<CR>
nnoremap <leader>se :vim //jg ***<Left><Left><Left><Left><Left><Left><Left>
nnoremap <leader>sq :%s:::g<Left><Left><Left>
nnoremap <leader>sr :cfdo %s:::gc<Left><Left><Left><Left>
nnoremap <leader>st :/^\*\*\*\*$<Left><Left><Left><Left><Left>
nnoremap <leader>su :w !sudo tee % <CR><CR>
nnoremap <leader>sw :%s:::cg<Left><Left><Left><Left>
nnoremap <leader>tb :tabnew<CR>
nnoremap <leader>tt :term<CR>
nmap ,tt yiw:call AddTag('<C-R>"')<CR>
vmap ,t y:call AddTag('<C-R>"')<CR>
nnoremap <leader>tn :VimwikiTable 
nnoremap <leader>tl :VimwikiTableMoveColumnLeft<CR>
nnoremap <leader>tr :VimwikiTableMoveColumnRight<CR>
nnoremap <leader>v :vsplit<CR>
nnoremap <leader>wc :Calendar<CR>
nnoremap <leader>wd <Plug>VimwikiDeleteFile<CR>
nnoremap <leader>wi :Diary<CR>
nnoremap <leader>wn <Plug>VimwikiMakeDiaryNote<CR>
nnoremap <leader>wr <Plug>VimwikiRenameFile<CR>
nnoremap <leader>ws <Plug>VimwikiUISelect
nnoremap <leader>wt <Plug>VimwikiMakeTomorrowDiaryNote<CR>
nnoremap <leader>ww <Plug>VimwikiIndex<CR>
nnoremap <leader>wy <Plug>VimwikiMakeYesterdayDiaryNote<CR>
nnoremap <Leader>wa :call VimwikiFindAllIncompleteTasks()<CR>
nnoremap <Leader>wx :call VimwikiFindIncompleteTasks()<CR>
nnoremap <leader>x :close<CR>
" refocus folds; close any other fold except the one that you are on
nnoremap <leader>z zMzvzz
nmap ]h <Plug>(GitGutterNextHunk)
nmap [h <Plug>(GitGutterPrevHunk)

"Esc
nnoremap <silent> <Esc><Esc> <Esc>:nohlsearch<CR><Esc>
nnoremap <Tab> >>

" Ctrl mapping
" Ctrl-n/m deletes blank line below/above
nnoremap <silent><C-m> m`:silent -g/\m^\s*$/d<CR>``:noh<CR>
nnoremap <silent><C-n> m`:silent +g/\m^\s*$/d<CR>``:noh<CR>
" nnoremap <silent><C-u> :bnext<CR>
" nnoremap <silent><C-i> :bprev<CR>

" ALT mappings
if !has('gui_running')
  set ttimeoutlen=10
  augroup FastEscape
    autocmd!
    " can break <esc> mapping in isert mode - switch from 0 to 200
    autocmd InsertEnter * set timeoutlen=200
    autocmd InsertLeave * set timeoutlen=2000
  augroup END
endif
 
function! Altmap(char)
  if has('gui_running') | return ' <A-'.a:char.'> ' | else | return ' <Esc>'.a:char.' '|endif
endfunction
 
" Make adjusing split sizes a bit more friendly
execute 'nnoremap <silent>'.Altmap('n').':vertical resize +3<CR>'
execute 'nnoremap <silent>'.Altmap('m').':vertical resize -3<CR>'
execute 'nnoremap <silent>'.Altmap('p').':resize -3<CR>'
execute 'nnoremap <silent>'.Altmap(';').':resize +3<CR>'
" Alt-i/o insert blank line below/above
execute 'nnoremap <silent>'.Altmap('o').':set paste<CR>m`O<Esc>``:set nopaste<CR>'
execute 'nnoremap <silent>'.Altmap('i').':set paste<CR>m`o<Esc>``:set nopaste<CR>'
"Moving tabs
execute 'nnoremap <silent>'.Altmap('r').':tabm -1<CR>'
execute 'nnoremap <silent>'.Altmap('t').':tabm +1<CR>'
execute 'nnoremap <silent>'.Altmap('f').':bnext<CR>'
execute 'nnoremap <silent>'.Altmap('g').':bprev<CR>'
"select all
execute 'nnoremap <silent>'.Altmap('q').'ggVG'

"Shift mapping
" move to previos tab
nnoremap <S-h> gT
" move to next tab
nnoremap <S-l> gt
nnoremap <S-Tab> <<
" nnoremap <S-j> :bnext<CR>
" nnoremap <S-k> :bprev<CR>

" disable arrows
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

"^^^^^^^^^Function keys^^^^^^^^^^^^
nnoremap <F1> :set spell!<CR>
"enable/disable spellchecking
nnoremap <F2> :set relativenumber!<CR>
"enable/disable relativenumber
nnoremap <F3> :set foldopen-=search \| set foldopen<CR>
" turn off folder search
nnoremap <F4> :set foldopen+=search \| set foldopen<CR>
" turn on folder search
nnoremap <F5> :set list! list?<CR>
" turn on/off list
nnoremap <F6> :call ToggleWrap()<CR>
nnoremap <F7> :set fileencodings=uft-8,cp1251<CR>:e<CR>
" nnoremap <F8> :sbnext<CR>
nnoremap <F8> :set invpaste paste?<CR>
set pastetoggle=<F8>
nnoremap <F9> :autocmd! TextChanged *
nnoremap <F10> :autocmd TextChanged * silent! write

" ^^^^^COMAND MODE^^^^^
"????????
" cmap ;\ \(\)<Left><Left>

"^^^^^^ INSERT MODE^^^^^^
inoremap <F5> <C-R>=strftime("%Y-%m-%d %H:%M:%S")<CR>
inoremap <F6> <C-R>=strftime("%Y-%m-%d")<CR>
"switch to rus lang
inoremap <C-l> <c-^>
" inoremap ;; <c-3>
inoremap ;; <esc>

"^^^^^VISUAL MODE^^^^^
vmap <leader>w <Esc>:call VisualHTMLTagWrap()<CR>

 
" }}}
" ----------TEST--------- {{{



"  }}}

